## Assignment Project – Singapore Jobs Analytics
Design a simple data product (dashboard or web app) using a real-world CSV of Singapore job postings (~1M+ rows). 
Your goal is to solve a clear business problem for a specific user group using insights from the data.

### 0. Preamble

In [211]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import numpy as np
import json

# Show every single row
pd.set_option('display.max_rows', None)

# Show every single column
pd.set_option('display.max_columns', None)

# Show full text inside cells without cutting it off
pd.set_option('display.max_colwidth', None)

### 1. Exploratory Data Analysis
The original file has 1048585 entries.

In [183]:
# replace with your actual file path/name
# re-adjust the nrows parameter as needed to read more or fewer rows from the CSV file
#df = pd.read_csv("SGJobData.csv", nrows=50000)
df = pd.read_csv("SGJobData.csv")

#### 1.1. Initial Information Gathering

In [184]:
df.head()

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,occupationId,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary
0,"[{""id"":13,""category"":""Environment / Health""},{""id"":25,""category"":""Manufacturing""},{""id"":36,""category"":""Sciences / Laboratory / R&D""}]",Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,NaN,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,"Food Technologist - Clementi | Entry Level | Up to $2,800",2400.0
1,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,2,2,NaN,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,Monthly,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up to $ 5.5K) - DS",4750.0
2,"[{""id"":33,""category"":""Repair and Maintenance""}]",Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,3,1,NaN,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,Monthly,0,Closed,Senior Technician,4200.0
3,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,8,1,NaN,Senior Executive,TRUST RECRUIT PTE. LTD.,10000,5000,Monthly,0,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, SharePoint) - DS",7500.0
4,"[{""id"":2,""category"":""Admin / Secretarial""}]",Full Time,2023-05-08,False,MCF-2023-0273976,2023-04-08,2023-04-08,0,3,99,2,3,NaN,Non-executive,EATZ CATERING SERVICES PTE. LTD.,3400,2400,Monthly,0,Closed,Sales / Admin Cordinator,2900.0

In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048585 entries, 0 to 1048584
Data columns (total 22 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1048585 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1048585 non-null  int64
 8   metadata_totalNumberJobApplication  1048585 non-null  int64
 9   metadata_totalNumberOfView          1048585 non-null  int64
 10  minimumYearsExperience              1048585 non-null  int64
 11  numberOfVacancies                   1048585 non-null  int64
 12  occupationId                        0 non-null        float64
 13  positionLevels                      1044597 non-null  object
 14  postedCompany_name                  1044597 non-null  object
 15  salary_maximum                      1048585 non-null  int64
 16  salary_minimum                      1048585 non-null  int64
 17  salary_type                         1044597 non-null  object
 18  status_id                           1048585 non-null  int64
 19  status_jobStatus                    1044597 non-null  object
 20  title                               1044597 non-null  object
 21  average_salary                      1048585 non-null  float64
dtypes: bool(1), float64(2), int64(8), object(11)
memory usage: 169.0+ MB

In [186]:
df.describe()

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,occupationId,salary_maximum,salary_minimum,status_id,average_salary
count,1.048585e+06,1.048585e+06,1.048585e+06,1.048585e+06,1.048585e+06,0.0,1.048585e+06,1.048585e+06,1048585.0,1.048585e+06
mean,5.472327e-02,2.136571e+00,2.674536e+01,2.779573e+00,2.680043e+00,NaN,5.723578e+03,3.815312e+03,0.0,4.769445e+03
std,2.822675e-01,1.062612e+01,8.262001e+01,2.537049e+00,1.124301e+01,NaN,5.018387e+04,3.172182e+03,0.0,2.547809e+04
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.0,0.000000e+00
25%,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,NaN,3.300000e+03,2.500000e+03,0.0,2.900000e+03
50%,0.000000e+00,0.000000e+00,4.000000e+00,2.000000e+00,1.000000e+00,NaN,4.500000e+03,3.000000e+03,0.0,3.800000e+03
75%,0.000000e+00,1.000000e+00,1.700000e+01,4.000000e+00,2.000000e+00,NaN,6.500000e+03,4.500000e+03,0.0,5.500000e+03
max,2.000000e+00,1.342000e+03,8.190000e+03,8.800000e+01,9.990000e+02,NaN,2.533000e+07,3.500000e+05,0.0,1.266640e+07

`occupationId` and `status_id` have no meaningful data and are not in the data dictionary. Let's drop them.

In [187]:
# drop columns occupationId and status_id as they are not needed for the analysis
df.drop(columns=["occupationId", "status_id"], inplace=True)

In [188]:
df.describe(include="object")

,categories,employmentTypes,metadata_expiryDate,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,positionLevels,postedCompany_name,salary_type,status_jobStatus,title
count,1044597,1044597,1044597,1044597,1044597,1044597,1044597,1044597,1044597,1044597,1044597
unique,21125,8,453,1044597,431,603,9,53151,1,3,377084
top,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-07-28,MCF-2023-0252866,2023-06-09,2023-07-14,Executive,THE SUPREME HR ADVISORY PTE. LTD.,Monthly,Open,SUPERVISOR
freq,92869,458139,4487,1,4508,4029,253701,61638,1044597,902614,8331

`salary_type` contains only `Monthly`. We take note of this for the context of our presentation.
We can also drop this.

In [189]:
df.drop(columns=["salary_type"], inplace=True)

`metadata_expiryDate`, `metadata_newPostingDate` and `metadata_originalPostingDate` can be converted to datetime.

In [190]:
date_cols = ["metadata_expiryDate", "metadata_newPostingDate", "metadata_originalPostingDate"]

for col in date_cols:
    df[col] = pd.to_datetime(df[col])

df.describe(datetime_is_numeric=True)

,metadata_expiryDate,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,average_salary
count,1044597,1044597,1044597,1.048585e+06,1.048585e+06,1.048585e+06,1.048585e+06,1.048585e+06,1.048585e+06,1.048585e+06,1.048585e+06
mean,2023-11-29 13:29:03.937231360,2023-11-03 21:37:33.521692672,2023-11-01 04:03:04.735741184,5.472327e-02,2.136571e+00,2.674536e+01,2.779573e+00,2.680043e+00,5.723578e+03,3.815312e+03,4.769445e+03
min,2023-04-04 00:00:00,2023-02-24 00:00:00,2022-10-03 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2023-08-18 00:00:00,2023-07-24 00:00:00,2023-07-21 00:00:00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.300000e+03,2.500000e+03,2.900000e+03
50%,2023-11-24 00:00:00,2023-10-30 00:00:00,2023-10-30 00:00:00,0.000000e+00,0.000000e+00,4.000000e+00,2.000000e+00,1.000000e+00,4.500000e+03,3.000000e+03,3.800000e+03
75%,2024-03-16 00:00:00,2024-02-20 00:00:00,2024-02-20 00:00:00,0.000000e+00,1.000000e+00,1.700000e+01,4.000000e+00,2.000000e+00,6.500000e+03,4.500000e+03,5.500000e+03
max,2024-12-12 00:00:00,2024-05-29 00:00:00,2024-05-29 00:00:00,2.000000e+00,1.342000e+03,8.190000e+03,8.800000e+01,9.990000e+02,2.533000e+07,3.500000e+05,1.266640e+07
std,NaN,NaN,NaN,2.822675e-01,1.062612e+01,8.262001e+01,2.537049e+00,1.124301e+01,5.018387e+04,3.172182e+03,2.547809e+04

`metadata_jobPostId` is the Unique ID. Drop NULL rows. Drop duplicates.

In [191]:
# Count rows where metadata_jobPostId is NULL
print(f"Number of rows where metadata_jobPostId is NULL: {df[df['metadata_jobPostId'].isnull()].shape[0]}")

Number of rows where metadata_jobPostId is NULL: 3988

In [192]:
# Drop rows where metadata_jobPostId is NULL
df = df[df["metadata_jobPostId"].notnull()]
# Show rows where metadata_jobPostId is duplicate
df[df["metadata_jobPostId"].duplicated(keep=False)].sort_values(by="metadata_jobPostId")

Empty DataFrame
Columns: [categories, employmentTypes, metadata_expiryDate, metadata_isPostedOnBehalf, metadata_jobPostId, metadata_newPostingDate, metadata_originalPostingDate, metadata_repostCount, metadata_totalNumberJobApplication, metadata_totalNumberOfView, minimumYearsExperience, numberOfVacancies, positionLevels, postedCompany_name, salary_maximum, salary_minimum, status_jobStatus, title, average_salary]
Index: []

Examine string columns `employmentTypes`, `positionLevels`, `postedCompany_name`, `status_jobStatus`, `title`.   
Examine bool column `metadata_isPostedOnBehalf`.

In [193]:
str_cols = ["employmentTypes", "positionLevels", "status_jobStatus", "metadata_isPostedOnBehalf"]
# count the number of unique values for each of the string columns
for col in str_cols:
    print(f"Value counts for {col}:")
    print(df[col].value_counts())
    print()

Value counts for employmentTypes:
Permanent                458139
Full Time                393352
Contract                 139182
Part Time                 25431
Temporary                 18241
Internship/Attachment      6959
Freelance                  2139
Flexi-work                 1154
Name: employmentTypes, dtype: int64

Value counts for positionLevels:
Executive            253701
Junior Executive     167656
Non-executive        131608
Fresh/entry level    118661
Professional         112208
Manager              110122
Senior Executive     100459
Middle Management     27375
Senior Management     22807
Name: positionLevels, dtype: int64

Value counts for status_jobStatus:
Open       902614
Closed     119701
Re-open     22282
Name: status_jobStatus, dtype: int64

Value counts for metadata_isPostedOnBehalf:
False    982729
True      61868
Name: metadata_isPostedOnBehalf, dtype: int64

#### 1.2. Cleaning Unrealistic Entries

In [194]:
# Limits
EXPERIENCE_CEILING = 20
SALARY_CEILING = 60000
SALARY_FLOOR = 500

Examine int columns `metadata_repostCount`, `metadata_totalNumberJobApplication`, `metadata_totalNumberOfView`, `minimumYearsExperience`, `numberOfVacancies`.

In [195]:
df["metadata_repostCount"].value_counts()
df["metadata_totalNumberJobApplication"].value_counts()
df["metadata_totalNumberOfView"].value_counts()

# list minimumYearsExperience and numberOfVacancies in ascending order
df["minimumYearsExperience"].value_counts().sort_index()
# count listings with minimumYearsExperience greater than EXPERIENCE_CEILING
print(f"Number of listings with minimumYearsExperience greater than {EXPERIENCE_CEILING}: {df[df['minimumYearsExperience'] > EXPERIENCE_CEILING].shape[0]}")
# cap minimumYearsExperience at EXPERIENCE_CEILING
df.loc[df["minimumYearsExperience"] > EXPERIENCE_CEILING, "minimumYearsExperience"] = EXPERIENCE_CEILING
df[df["minimumYearsExperience"] > EXPERIENCE_CEILING].shape[0]

df["numberOfVacancies"].value_counts().sort_index()

0    1001867
1      28078
2      14652
Name: metadata_repostCount, dtype: int64

0       656375
1       246159
2        23284
3        16627
4        12949
5        10200
6         8369
7         6736
8         5981
9         5116
10        4446
11        3734
12        3314
13        2939
14        2579
15        2326
16        2196
17        2037
18        1778
19        1578
20        1418
21        1345
22        1249
23        1130
24        1066
26         962
25         939
27         864
29         785
28         770
30         673
31         662
32         617
33         565
35         532
34         517
36         466
39         427
37         427
38         409
40         363
41         337
44         333
42         331
43         323
45         302
48         269
46         260
52         231
47         223
49         220
51         212
50         210
53         210
54         201
56         176
60         162
57         162
55         154
58         152
59         150
64         146
63         132
61         125
62         119
65         116
66         111
67         106
68          97
69          94
74          93
72          91
73          91
70          91
75          90
71          87
86          78
77          78
82          75
80          74
85          73
76          73
81          72
83          71
84          71
79          70
78          67
90          65
88          65
96          59
89          57
92          55
87          54
91          50
98          47
95          45
99          45
97          43
94          43
103         42
93          41
100         41
101         41
106         39
105         37
108         36
109         36
104         33
117         32
102         31
119         31
112         30
107         29
111         29
120         28
114         28
116         27
110         26
140         26
134         26
133         26
129         26
115         25
139         25
122         24
118         24
152         23
113         23
126         22
128         22
130         21
138         21
145         20
127         19
123         19
125         19
136         18
121         17
137         17
124         17
132         16
143         16
131         15
141         15
144         15
150         15
146         14
147         14
168         13
160         13
175         13
151         13
163         13
156         13
157         12
165         12
148         12
171         12
164         12
155         12
153         12
149         11
142         11
161         11
176         11
159         11
170         10
182         10
194         10
179         10
169         10
135         10
174          9
162          9
180          9
183          8
173          8
197          8
190          8
154          8
184          7
167          7
158          7
166          7
185          7
196          7
172          7
215          7
203          6
234          6
207          6
188          6
192          6
206          6
212          6
218          6
177          6
204          5
216          5
223          5
256          5
228          5
178          5
193          5
213          5
237          5
209          5
200          5
230          5
198          5
199          5
195          5
191          5
208          5
201          4
250          4
235          4
229          4
240          4
224          4
219          4
239          4
211          4
300          4
236          4
189          4
231          4
287          4
245          4
214          4
217          3
257          3
220          3
248          3
344          3
297          3
186          3
285          3
225          3
305          3
181          3
270          3
233          3
210          3
243          3
232          3
249          3
269          3
226          3
251          3
341          2
286          2
254          2
255          2
421          2
263          2
268          2
278          2
253          2
222          2
280          2
187          2
465          2
252          2
384          2
299          2
302          2
332          2
282          2
477          2
359          2
202          2
244          2
238          2
290          2
626          1
522          1
391          1
336          1
348          1
504          1
663          1
921          1
352          1
264          1
591          1
429          1
1052         1
272          1
306          1
267          1
567          1
316          1
342          1
283          1
298          1
279          1
689          1
1342         1
678          1
313          1
241          1
303          1
365          1
323          1
351          1
580          1
1111         1
247          1
221          1
284          1
422          1
353          1
310          1
914          1
1199         1
470          1
401          1
326          1
442          1
312          1
354          1
356          1
372          1
448          1
629          1
320          1
1048         1
261          1
277          1
377          1
227          1
476          1
329          1
435          1
389          1
376          1
525          1
492          1
460          1
293          1
296          1
276          1
620          1
527          1
346          1
289          1
922          1
318          1
581          1
319          1
708          1
275          1
292          1
599          1
345          1
362          1
785          1
846          1
602          1
274          1
507          1
434          1
531          1
499          1
415          1
395          1
260          1
466          1
394          1
324          1
242          1
366          1
334          1
374          1
632          1
Name: metadata_totalNumberJobApplication, dtype: int64

0       179121
1       127738
2        96349
3        73658
4        57729
5        46099
6        36979
7        30012
8        25302
9        21025
10       17799
11       15252
12       13320
13       11836
14       10350
15        9567
16        8714
17        8026
18        7500
19        7053
20        6774
21        6304
22        6052
23        5644
24        5336
25        5217
26        4930
27        4661
28        4464
29        4166
30        4092
31        3864
32        3748
34        3552
33        3509
35        3220
36        3103
37        3043
38        2912
39        2758
41        2717
40        2705
43        2510
42        2444
44        2352
45        2327
46        2239
47        2187
48        2094
50        1928
49        1919
51        1896
53        1864
52        1857
54        1789
55        1653
57        1638
56        1625
59        1613
58        1545
62        1519
61        1513
60        1513
64        1424
63        1382
65        1363
66        1341
68        1271
67        1262
69        1235
71        1220
72        1220
70        1210
73        1156
74        1117
75        1108
76        1082
77        1079
79        1066
78        1034
80        1007
82         999
81         993
83         984
84         973
85         970
86         931
87         908
88         904
89         892
90         892
92         839
91         827
97         808
93         803
96         797
95         782
105        758
94         747
100        736
99         734
98         733
102        691
103        685
101        671
104        664
106        656
109        650
111        634
112        621
108        614
107        614
116        610
114        608
113        605
110        601
117        589
118        551
121        550
124        548
120        546
126        542
123        519
128        515
115        512
119        510
122        502
127        502
125        498
129        489
135        486
134        473
133        470
130        466
136        461
137        459
139        453
132        450
142        432
131        423
140        422
143        412
144        411
138        403
147        403
154        401
141        400
159        400
149        392
148        387
153        385
146        378
150        359
145        356
161        353
151        352
158        347
160        344
157        343
155        341
164        338
156        334
167        330
172        328
163        324
152        322
162        320
168        320
171        313
166        310
169        310
174        305
176        304
170        300
178        297
165        294
175        293
181        289
180        289
173        280
179        274
187        273
177        272
191        269
184        268
185        268
183        268
188        262
186        256
197        249
189        240
190        237
193        234
198        230
182        229
199        228
192        227
207        223
195        221
201        219
204        218
200        217
194        216
205        210
203        205
219        203
202        203
218        200
212        200
206        196
208        196
213        196
223        195
227        194
215        194
216        192
209        191
211        190
214        189
196        187
234        184
221        184
222        183
217        183
210        182
226        178
233        177
239        174
228        171
248        170
225        170
236        169
235        168
232        166
238        164
230        162
245        162
229        160
220        159
237        156
231        155
247        153
242        150
246        148
251        147
224        146
264        145
250        142
249        140
252        140
254        138
253        136
241        135
257        132
268        131
243        128
258        127
240        127
259        126
262        125
244        124
261        124
276        122
271        121
267        120
255        120
292        118
279        118
284        117
275        115
263        115
277        114
274        114
266        114
286        114
285        113
260        112
282        110
272        109
270        109
273        109
287        106
256        105
280        104
281        104
269        102
283        100
296         98
288         97
291         97
300         96
265         96
294         95
308         95
303         94
306         93
297         93
309         93
278         93
322         92
301         92
289         90
290         90
295         89
305         87
311         87
326         86
299         86
315         85
323         84
293         83
314         83
317         83
319         82
331         82
304         81
332         80
334         78
333         78
312         78
307         76
325         76
338         75
318         75
321         75
345         73
343         73
298         73
324         72
316         72
328         72
341         71
327         71
302         70
329         69
313         69
363         68
310         68
342         67
337         66
344         65
339         64
330         63
335         63
340         63
356         62
351         62
320         62
366         61
368         61
354         61
376         60
367         60
358         59
402         59
372         58
348         58
355         57
346         57
360         56
357         55
352         55
362         55
361         55
400         55
426         55
380         55
410         55
420         55
349         54
391         54
378         54
388         53
371         53
374         53
382         51
389         51
421         51
336         50
403         50
350         50
386         49
406         48
377         48
347         48
353         47
387         47
390         47
408         47
399         46
385         46
407         46
429         46
383         46
384         45
413         45
393         45
369         45
365         45
381         44
418         44
397         44
396         44
370         43
379         43
373         43
359         43
392         43
436         43
422         43
427         43
412         42
364         42
452         41
446         41
473         41
440         40
411         40
414         39
395         39
398         39
405         38
437         37
430         37
424         36
428         36
415         36
442         36
451         36
394         36
435         36
494         36
416         36
441         35
375         35
425         34
483         34
423         34
401         34
404         34
462         33
466         33
433         33
449         33
457         32
443         32
439         32
447         32
458         32
434         31
432         31
455         31
409         31
488         30
529         30
500         30
469         30
470         30
464         30
518         29
481         29
467         29
486         29
461         29
465         29
484         29
515         29
419         29
508         28
491         28
478         28
445         28
489         28
463         28
450         27
459         27
498         27
453         27
460         27
438         27
468         27
480         26
497         26
417         26
475         26
507         26
454         26
476         26
520         26
528         26
517         26
485         25
502         25
546         25
505         25
519         25
471         24
523         24
482         24
474         24
487         24
509         24
496         24
618         24
513         23
557         23
431         23
490         23
506         23
479         22
495         22
511         22
499         22
456         22
544         22
609         22
585         22
477         22
516         22
540         22
448         22
527         22
532         21
541         21
555         21
522         21
510         21
521         21
574         21
493         21
501         21
535         21
594         21
554         20
534         20
592         20
552         20
503         20
472         20
549         20
644         20
547         20
584         20
551         20
564         20
581         19
565         19
569         19
562         19
556         18
566         18
621         18
539         18
599         18
568         18
576         18
567         18
588         18
512         18
680         18
582         17
578         17
525         17
504         17
538         17
563         17
606         17
637         16
600         16
633         16
550         16
526         16
598         16
617         15
444         15
665         15
524         15
586         15
543         15
553         15
570         15
577         15
492         15
604         15
560         15
703         15
559         15
561         15
536         14
622         14
624         14
589         14
631         14
591         14
645         14
575         14
587         14
629         14
537         14
697         13
657         13
530         13
677         13
619         13
642         13
579         13
545         13
615         13
685         13
531         13
597         13
514         13
608         13
607         13
605         13
696         13
809         13
614         13
595         13
548         13
590         13
663         12
613         12
668         12
652         12
643         12
666         12
704         12
702         12
669         12
611         12
638         12
664         12
580         11
558         11
625         11
732         11
653         11
616         11
650         11
533         11
641         11
632         11
671         11
706         11
603         11
700         10
679         10
659         10
689         10
626         10
573         10
640         10
698         10
683         10
740         10
635         10
656         10
767         10
707         10
655         10
688         10
737         10
682         10
647         10
572         10
724         10
694         10
630         10
695         10
654         10
712         10
686         10
768          9
691          9
726          9
777          9
634          9
693          9
728          9
810          9
780          9
627          9
623          9
699          9
719          9
779          9
833          9
628          9
687          9
661          9
713          9
675          9
620          9
658          9
735          9
610          9
636          9
708          9
759          9
612          9
748          8
723          8
602          8
649          8
651          8
751          8
773          8
601          8
781          8
646          8
813          8
875          8
908          8
885          8
596          8
583          8
571          8
750          8
662          8
681          8
744          8
852          8
684          8
858          8
786          8
741          8
764          8
660          8
720          8
1003         8
648          8
674          8
542          8
593          8
745          8
784          7
670          7
890          7
743          7
639          7
739          7
886          7
758          7
844          7
1002         7
850          7
715          7
802          7
791          7
749          7
838          7
898          7
847          7
727          7
873          7
785          7
774          7
899          7
730          7
905          7
721          7
842          7
714          7
878          7
678          7
673          7
849          7
980          7
738          7
812          7
716          6
1051         6
772          6
1035         6
866          6
869          6
861          6
801          6
995          6
927          6
788          6
913          6
840          6
790          6
804          6
837          6
825          6
667          6
799          6
848          6
916          6
1302         6
794          6
760          6
930          6
955          6
944          6
754          6
895          6
807          6
787          6
770          6
701          6
692          6
722          6
936          5
823          5
824          5
803          5
1057         5
868          5
717          5
783          5
894          5
765          5
877          5
806          5
1001         5
757          5
900          5
831          5
867          5
778          5
769          5
954          5
672          5
949          5
782          5
816          5
718          5
797          5
1064         5
820          5
756          5
746          5
843          5
984          5
859          5
1066         5
792          5
761          5
841          5
796          5
815          5
736          5
921          5
775          5
1098         5
972          5
857          5
709          5
1145         4
1295         4
763          4
725          4
747          4
1126         4
1027         4
733          4
1096         4
795          4
819          4
734          4
1046         4
1281         4
996          4
1118         4
805          4
863          4
957          4
800          4
864          4
933          4
729          4
971          4
911          4
994          4
967          4
969          4
1023         4
952          4
711          4
1365         4
1115         4
997          4
922          4
1029         4
924          4
828          4
818          4
874          4
690          4
817          4
836          4
914          4
798          4
892          4
860          4
983          4
829          4
1045         4
771          4
950          4
1026         4
925          4
876          4
1007         4
856          4
947          4
998          3
902          3
1387         3
1042         3
753          3
920          3
731          3
865          3
789          3
834          3
1070         3
1214         3
1110         3
963          3
897          3
1259         3
862          3
1445         3
884          3
1068         3
1333         3
851          3
1093         3
985          3
1077         3
1471         3
942          3
1084         3
766          3
959          3
1102         3
982          3
1101         3
1356         3
1067         3
1221         3
1074         3
912          3
1198         3
882          3
1079         3
1317         3
1371         3
939          3
1028         3
928          3
1008         3
1138         3
830          3
993          3
1330         3
1082         3
752          3
1010         3
839          3
1129         3
923          3
1375         3
981          3
941          3
961          3
943          3
826          3
855          3
1307         3
1992         3
1197         3
1043         3
1124         3
872          3
1322         3
1166         3
1004         3
1069         3
822          3
853          3
1144         3
1095         3
808          3
883          3
990          3
870          3
1060         3
1161         3
1065         3
762          3
935          3
1058         3
846          3
1025         3
1478         3
976          3
1021         3
953          3
776          3
821          3
965          3
940          2
1250         2
1415         2
1209         2
1146         2
975          2
1112         2
710          2
1173         2
1005         2
1724         2
793          2
1521         2
956          2
1244         2
1450         2
1131         2
1015         2
1618         2
1083         2
1218         2
1293         2
1332         2
1033         2
1030         2
1063         2
1224         2
1336         2
1172         2
1546         2
1750         2
1745         2
1374         2
1196         2
1195         2
1089         2
987          2
1519         2
906          2
880          2
1352         2
1104         2
1040         2
827          2
1225         2
978          2
937          2
1170         2
879          2
1111         2
891          2
901          2
1097         2
1811         2
1009         2
1139         2
1563         2
1151         2
1038         2
1282         2
1216         2
1553         2
1016         2
1580         2
1141         2
1188         2
1090         2
904          2
1094         2
1125         2
1303         2
888          2
1978         2
1155         2
1011         2
1013         2
1328         2
1053         2
1050         2
1022         2
992          2
1422         2
1234         2
1000         2
931          2
881          2
1239         2
1560         2
1142         2
1189         2
1355         2
1334         2
958          2
1106         2
1020         2
1251         2
1160         2
832          2
1034         2
1233         2
1274         2
1204         2
1287         2
1351         2
1180         2
977          2
1116         2
1354         2
948          2
989          2
1088         2
1017         2
907          2
1191         2
1647         2
979          2
705          2
1208         2
966          2
1075         2
1006         2
1087         2
845          2
919          2
1049         2
1756         2
1414         2
1135         2
1024         2
1052         2
1389         2
1178         2
893          2
1343         2
951          2
918          2
988          2
932          2
917          2
1150         2
974          2
1162         2
1163         2
946          2
1370         2
2122         2
1439         2
1108         2
968          2
903          2
2040         2
1037         2
1205         2
1174         2
973          2
1278         2
1177         2
1156         2
742          2
929          2
1242         2
1805         2
1505         2
1078         2
1130         2
1359         2
1316         2
1014         2
887          2
1243         1
2815         1
1140         1
1280         1
1909         1
1843         1
1652         1
1741         1
755          1
1594         1
1766         1
1275         1
1672         1
1880         1
1689         1
1290         1
1955         1
1498         1
2170         1
2230         1
2322         1
2461         1
2378         1
1099         1
1041         1
1121         1
1650         1
1506         1
7491         1
1091         1
4825         1
1404         1
3259         1
1455         1
896          1
1192         1
4204         1
3737         1
3058         1
4095         1
1626         1
8103         1
7521         1
2014         1
1604         1
2559         1
1123         1
1754         1
1883         1
1511         1
1086         1
2744         1
2370         1
3057         1
1688         1
1134         1
1459         1
3912         1
1543         1
2157         1
1903         1
4138         1
1482         1
854          1
1410         1
1453         1
1388         1
1613         1
1697         1
2586         1
2314         1
4614         1
1412         1
970          1
1516         1
2114         1
2281         1
1327         1
2315         1
2410         1
1658         1
1122         1
2207         1
3025         1
1965         1
1206         1
926          1
1558         1
1865         1
1637         1
2086         1
1631         1
4224         1
2025         1
2015         1
1212         1
1238         1
1617         1
1710         1
1376         1
1397         1
1897         1
1677         1
1276         1
1235         1
1416         1
1128         1
1323         1
1340         1
1019         1
2800         1
2305         1
814          1
1683         1
1171         1
1977         1
1361         1
1838         1
1919         1
835          1
1184         1
3133         1
1143         1
1918         1
1663         1
1705         1
1753         1
3080         1
1384         1
1313         1
1194         1
1105         1
1584         1
2113         1
1458         1
1012         1
1933         1
945          1
1133         1
1127         1
1526         1
1318         1
2246         1
1884         1
1607         1
811          1
1372         1
1481         1
1681         1
1743         1
962          1
1381         1
1120         1
2445         1
2027         1
1467         1
1113         1

0     114451
1     264085
2     219909
3     169787
4      34982
5     145154
6      20244
7      11569
8      27443
9       1170
10     26604
11       207
12      2621
13       204
14       156
15      4748
16        68
17        34
18       117
19        17
20       752
21         5
22        21
23         5
24         2
25       110
26         4
27         4
28         3
29         3
30        79
31         4
32         2
33         3
35         6
38         1
40         2
47         1
50         3
55         2
56         2
58         1
59         2
60         1
61         2
62         1
63         1
76         1
87         2
88         2
Name: minimumYearsExperience, dtype: int64

Number of listings with minimumYearsExperience greater than 20: 275

0

1      590242
2      195718
3      111947
4       24580
5       64760
6        5456
7        2349
8        5542
9         487
10      26547
11        182
12        596
13        128
14        158
15       2381
16         60
17         60
18        117
19         97
20       5162
21         34
22         37
23         22
24         48
25        289
26          8
27         44
28        112
29         44
30       2920
31         11
32         24
33         20
34          5
35         30
36         23
37         13
38         15
39          4
40        330
41          3
42          1
43          2
44         30
45          9
48         18
49         24
50       1270
51          5
54          6
55          5
57          1
58          1
59          2
60        133
62          1
64          2
65          2
67          1
69          3
70        136
80        149
86          9
88          3
90         15
98          3
99         70
100      1783
101         1
102         1
103         1
108         3
110         3
111         1
119         1
120        16
121         1
123         2
133         1
140         2
150        30
155         1
163         1
165         1
200        83
201         1
202         1
204         1
224         1
250         2
291         1
300        13
302         1
328         1
400         4
499         1
500        45
505         1
510         1
579         1
682         1
693         1
845         1
900         1
902         1
998         1
999        78
Name: numberOfVacancies, dtype: int64

Examine float columns `salary_maximum`,	`salary_minimum`, `average_salary`.

In [196]:
# find number of rows where salary_minimum is less than SALARY_FLOOR
print(f"Number of rows where salary_minimum is less than {SALARY_FLOOR}: {df[df['salary_minimum'] < SALARY_FLOOR].shape[0]}")
# find number of rows where salary_maximum is greater than SALARY_CEILING
print(f"Number of rows where salary_maximum is greater than {SALARY_CEILING}: {df[df['salary_maximum'] > SALARY_CEILING].shape[0]}")

Number of rows where salary_minimum is less than 500: 9581
Number of rows where salary_maximum is greater than 60000: 435

In [197]:
# find the number of rows where average_salary is not the mean of salary_minimum and salary_maximum
df["average_salary"].equals((df["salary_minimum"] + df["salary_maximum"]) / 2)

True

In [198]:
# find the number of rows where salary_minimum is greater than salary_maximum
df[df["salary_minimum"] > df["salary_maximum"]].shape[0]

0

In [199]:
# add a new column "salary_OK" to indicate salary_minimum is greater than SALARY_FLOOR and salary_maximum is less than SALARY_CEILING
df["salary_OK"] = (df["salary_minimum"] >= SALARY_FLOOR) & (df["salary_maximum"] <= SALARY_CEILING)
df["salary_OK"].value_counts()

True     1034597
False      10000
Name: salary_OK, dtype: int64

#### 1.3. Investigate if `categories` JSON is clean

In [200]:
# Parse the JSON in the "categories" column into a list of dictionaries
df["categories_parsed"] = df["categories"].apply(json.loads)

# Are there any rows with empty categories?
empty_categories = df[df["categories_parsed"].apply(lambda x: len(x) == 0)]
print("Rows with empty categories:")
print(empty_categories.shape[0])

# Are there any rows with missing categories?
missing_categories = df[df["categories_parsed"].isnull()]
print("Rows with missing categories:")
print(missing_categories.shape[0])

# Are there any rows with duplicate categories? e.g. [{"category": "Software Engineer"}, {"category": "Software Engineer"}]
def has_duplicate_categories(categories):
    seen = set()
    for category in categories:
        cat_name = category.get("category")
        if cat_name in seen:
            return True
        seen.add(cat_name)
    return False
duplicate_categories = df[df["categories_parsed"].apply(has_duplicate_categories)]
print("Rows with duplicate categories:")
print(duplicate_categories.shape[0])

Rows with empty categories:
0
Rows with missing categories:
0
Rows with duplicate categories:
0

#### 1.4. Explode `categories` JSON

In [201]:
# Explode the "categories_parsed" column so that each category gets its own row
df_exploded = df.explode("categories_parsed")
# create new columns for category_id and category_name
df_exploded["category_id"] = df_exploded["categories_parsed"].apply(lambda x: x.get("id") if isinstance(x, dict) else None)
df_exploded["category_name"] = df_exploded["categories_parsed"].apply(lambda x: x.get("category") if isinstance(x, dict) else None)
df_exploded.head(3)

# List all unique categories sort by category_id
all_categories = df_exploded[["category_id", "category_name"]].drop_duplicates().sort_values(by="category_id")
all_categories

# Count the number of occurrences of each category
category_counts = df_exploded["category_name"].value_counts()
category_counts

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,positionLevels,postedCompany_name,salary_maximum,salary_minimum,status_jobStatus,title,average_salary,salary_OK,categories_parsed,category_id,category_name
0,"[{""id"":13,""category"":""Environment / Health""},{""id"":25,""category"":""Manufacturing""},{""id"":36,""category"":""Sciences / Laboratory / R&D""}]",Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,Closed,"Food Technologist - Clementi | Entry Level | Up to $2,800",2400.0,True,"{'id': 13, 'category': 'Environment / Health'}",13,Environment / Health
0,"[{""id"":13,""category"":""Environment / Health""},{""id"":25,""category"":""Manufacturing""},{""id"":36,""category"":""Sciences / Laboratory / R&D""}]",Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,Closed,"Food Technologist - Clementi | Entry Level | Up to $2,800",2400.0,True,"{'id': 25, 'category': 'Manufacturing'}",25,Manufacturing
0,"[{""id"":13,""category"":""Environment / Health""},{""id"":25,""category"":""Manufacturing""},{""id"":36,""category"":""Sciences / Laboratory / R&D""}]",Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,Closed,"Food Technologist - Clementi | Entry Level | Up to $2,800",2400.0,True,"{'id': 36, 'category': 'Sciences / Laboratory / R&D'}",36,Sciences / Laboratory / R&D

     category_id                      category_name
8              1   Accounting / Auditing / Taxation
4              2                Admin / Secretarial
19             3                Advertising / Media
12             4     Architecture / Interior Design
40             5                Banking and Finance
12             6          Building and Construction
5              7                         Consulting
23             8                   Customer Service
19             9                             Design
71            10             Education and Training
10            11                        Engineering
375           12                      Entertainment
0             13               Environment / Health
9             14                Events / Promotions
11            15                                F&B
27            16                 General Management
27            17                       General Work
97            18        Healthcare / Pharmaceutical
219           19                        Hospitality
60            20                    Human Resources
1             21             Information Technology
117           22                          Insurance
60            23                              Legal
8             24           Logistics / Supply Chain
0             25                      Manufacturing
19            26       Marketing / Public Relations
53            27         Medical / Therapy Services
68            28             Personal Care / Beauty
5             29              Professional Services
194           30             Public / Civil Service
41            31         Purchasing / Merchandising
24            32  Real Estate / Property Management
2             33             Repair and Maintenance
44            34                    Risk Management
8             35                     Sales / Retail
0             36        Sciences / Laboratory / R&D
7             37         Security and Investigation
151           38                    Social Services
10            39                 Telecommunications
756           40                   Travel / Tourism
12            41                             Others
40            42                    Wholesale Trade
10            43              Precision Engineering

Information Technology               140866
Engineering                          136372
Admin / Secretarial                  117854
Customer Service                     111785
Others                               106101
Sales / Retail                       105067
Building and Construction             84034
Accounting / Auditing / Taxation      78648
F&B                                   73731
Logistics / Supply Chain              69193
Banking and Finance                   62000
Manufacturing                         56437
Human Resources                       53465
Marketing / Public Relations          53442
Healthcare / Pharmaceutical           52741
Education and Training                44877
Consulting                            38961
General Management                    35397
General Work                          30140
Hospitality                           25165
Repair and Maintenance                23791
Professional Services                 20221
Sciences / Laboratory / R&D           19753
Advertising / Media                   19584
Design                                18512
Environment / Health                  17211
Events / Promotions                   16993
Personal Care / Beauty                16932
Purchasing / Merchandising            15382
Architecture / Interior Design        15353
Medical / Therapy Services            15351
Wholesale Trade                       11091
Legal                                 10737
Real Estate / Property Management     10513
Risk Management                        9390
Social Services                        8684
Insurance                              7994
Telecommunications                     7964
Precision Engineering                  6562
Travel / Tourism                       6549
Security and Investigation             5461
Entertainment                          4242
Public / Civil Service                 3283
Name: category_name, dtype: int64

#### 1.5. Write to File

In [212]:
# Write the cleaned DataFrame to a new CSV file
df.to_csv("SGJobData_cleaned.csv", index=False)
df_exploded.to_csv("SGJobData_exploded.csv", index=False)

### 2. Visualization with Streamlit

In [ ]:
%%writefile assignment.py
from pathlib import Path

import pandas as pd
import streamlit as st

DATA_PATH = Path(__file__).resolve().parent / "SGJobData_cleaned.csv"
df = pd.read_csv(
    DATA_PATH,
    parse_dates=[
        "metadata_newPostingDate",
        "metadata_originalPostingDate",
        "metadata_expiryDate",
    ],
)

EXPLODED_DATA_PATH = Path(__file__).resolve().parent / "SGJobData_exploded.csv"
df_exploded = pd.read_csv(
    EXPLODED_DATA_PATH,
    parse_dates=[
        "metadata_newPostingDate",
        "metadata_originalPostingDate",
        "metadata_expiryDate",
    ],
)

st.title("Singapore Job Market Dashboard")

with st.sidebar:
    st.header("Filters")
    category_options = sorted(df_exploded["category_name"].dropna().unique())
    selected_categories = st.multiselect(
        "Category", category_options, default=category_options
    )

    employment_options = sorted(df["employmentTypes"].dropna().unique())
    selected_employment = st.selectbox("Employment Type", ["All"] + employment_options)

    open_only = st.checkbox("Show only open postings")

    min_exp = int(df["minimumYearsExperience"].min())
    max_exp = int(df["minimumYearsExperience"].max())
    experience_range = st.slider(
        "Minimum Years Experience", min_exp, max_exp, (min_exp, max_exp)
    )

# df = df[df["primary_category"].isin(selected_categories)]
if selected_employment != "All":
    df = df[df["employmentTypes"] == selected_employment]
if open_only:
    df = df[df["status_jobStatus"] == "Open"]
df = df[df["minimumYearsExperience"].between(*experience_range)]

st.header("Overview")

col1, col2, col3 = st.columns(3)
col1.metric("Total Postings", len(df))
col2.metric(
    "Average Salary",
    f"${df['average_salary'].mean():,.0f}" if len(df) else "N/A",
)
col3.metric("Total Applications", int(df["metadata_totalNumberJobApplication"].sum()))

with st.expander("View raw data"):
    st.dataframe(df)

st.header("Trends & Breakdown")

postings_by_month = (
    df.groupby(df["metadata_newPostingDate"].dt.to_period("M")).size().rename("postings")
)
postings_by_month.index = postings_by_month.index.to_timestamp()

# avg_salary_by_category = (
    # df.groupby("primary_category")["average_salary"].mean().sort_values(ascending=False)
# )

tab1, tab2, tab3 = st.tabs(["Trends", "Categories", "Salary"])

with tab1:
    st.subheader("Postings Over Time")
    st.line_chart(postings_by_month)
    st.subheader("Cumulative Postings")
    st.area_chart(postings_by_month.cumsum())

# with tab2:
    # st.subheader("Average Salary by Category")
    # st.bar_chart(avg_salary_by_category)

with tab3:
    st.subheader("Experience vs Salary")
    st.scatter_chart(df, x="minimumYearsExperience", y="average_salary")

Overwriting assignment.py